### ISSUE TITLE
Flex-grow 9999 Hack

### ISSUE THREAD

**Issue by nhducit** [jorenvanhee/jorenvanhee.github.io#2]
I think we can archive the same result with flex grow 1. Are there any different reason?
https://jsfiddle.net/JackMap/77eq6k2t/

**Comment by jorenvanhee** [comment]
Hi! You're not the first one with that question. Here's a screenshot that I sent to somebody with a similar question (with `flex-grow: 2`). As you can see, if the flex-grow value of item b is not 9999, then item A still grows.

![screenshot](https://cloud.githubusercontent.com/assets/231202/19162016/70cd08b8-8bf6-11e6-95dd-9f44174c84a4.jpg)

**Comment by nhducit** [comment]
Oh I see, thank you for you explanation
